
[window]
title = "Alacritty"
decorations = "none"
blur = true
opacity = 0.8
padding.x = 2
padding.y = 2
dynamic_padding = true

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape= "Beam"
blinking = "Never"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[colors.primary]
background = '#020819'

[terminal.shell]
program = "/bin/fish"
args = ["-l"]

[env]
TERM = "alacritty"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "MesloLGS Nerd Font"
normal.style = "Regular"
size = 13.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[general]
live_config_reload = true
working_directory = "None"

# Themes --
import = [ 
  #"~/.config/alacritty/nordic.toml",
  "~/.config/alacritty/keybinds.toml",
  #"~/.cache/wal/colors-alacritty.toml"
]
